---
title: "Stratification by Propensity Score Algorithm"
author: "N/A"
date: "3/29/2021"
output: html_document
---

```{r echo=FALSE, results = FALSE, include=FALSE}
if(!require(MatchIt)) install.packages("MatchIt", repos = "http://cran.us.r-project.org")
if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
if(!require(ggplot2)) install.packages("ggplot2", repos = "http://cran.us.r-project.org")
if(!require(lmtest)) install.packages("lmtest", repos = "http://cran.us.r-project.org")
if(!require(sandwich)) install.packages("sandwich", repos = "http://cran.us.r-project.org")
if(!require(broom)) install.packages("broom", repos = "http://cran.us.r-project.org")

library(MatchIt)
library(dplyr)
library(ggplot2)
library(lmtest) 
library(sandwich) 
library(broom)
```


## R Markdown

```{r Difference in Means Pre-Analysis, echo=FALSE}
# Reading in the datasets as R Dataframes
highDim_data = read.csv("/data/highDim_dataset.csv")
lowDim_data = read.csv("/data/lowDim_dataset.csv")

highDim_data %>% 
  group_by(A) %>% 
  summarise(n=n(),
            mean_outcome=mean(Y),
            std_error = sd(Y) / sqrt(n))

with(highDim_data, t.test(Y ~ A))

lowDim_data %>% 
  group_by(A) %>% 
  summarise(n=n(),
            mean_outcome=mean(Y),
            std_error = sd(Y) / sqrt(n))

with(lowDim_data, t.test(Y ~ A))
```



### Use Logistic regression to get the propensity score
```{r Propensity Score Estimation, echo=FALSE}
# High dimension dataset
ps_hd_est <- glm(A ~ . -Y,
                 family=binomial(), 
                 data=highDim_data)

ps_hd_df <- data.frame(prop_score = predict(ps_hd_est, type = "response"),
                       treatment = ps_hd_est$model$A,
                       Y = ps_hd_est$model$Y)
ps_hd_df %>%
  group_by(treatment) %>% 
  summarise(mean_prop_score=mean(prop_score))
  
labs <- paste("Actual treatment indicator:", c("Treated", "Control"))
ps_hd_df %>%
  mutate(treatment = ifelse(treatment == 1, labs[1], labs[2])) %>%
  ggplot(aes(x = prop_score)) +
  geom_histogram(color = "white") +
  facet_wrap(~treatment) +
  xlab("Probability of being exposed") +
  theme_bw()

# Low dimension dataset
ps_ld_est <- glm(A ~ . -Y,
                 family=binomial(), 
                 data=lowDim_data)

ps_ld_df <- data.frame(prop_score = predict(ps_ld_est, type = "response"),
                       treatment = ps_ld_est$model$A,
                       Y = ps_ld_est$model$Y)
ps_ld_df %>%
  group_by(treatment) %>% 
  summarise(mean_prop_score=mean(prop_score))
  
labs <- paste("Actual treatment indicator:", c("Treated", "Control"))
ps_ld_df %>%
  mutate(treatment = ifelse(treatment == 1, labs[1], labs[2])) %>%
  ggplot(aes(x = prop_score)) +
  geom_histogram(color = "white") +
  facet_wrap(~treatment) +
  xlab("Probability of being exposed") +
  theme_bw()
```

## Perform stratification and find difference of means and weights
```{r}


n_strat <- 7

#High Dimensional Data


hd_prep <- system.time({
  
  #Stratify the Data by Propensity score
  hd_strat_divider <- n_strat/nrow(ps_hd_df);
  strat_hd_df <- ps_hd_df %>% arrange(prop_score) %>%
    mutate(stratum =  as.integer((1:n() -.5)*hd_strat_divider ) + 1);
  
  #Differences in means
  diff_mean_hd <- strat_hd_df %>%
    group_by(treatment, stratum) %>%
    summarise(mean_treat = mean(Y), .groups = "keep") %>%
    mutate(mean_treat= if_else(treatment == 0, -mean_treat, mean_treat)) %>%
    ungroup(treatment) %>%
    mutate(diff_mean = sum(mean_treat)) %>%
    filter(treatment == 0) %>%
    select(stratum, diff_mean);

  #Weights for each stratum
  diff_weight_hd <- strat_hd_df %>%
    group_by(stratum) %>%
    tally() %>%
    mutate(weight = n/nrow(strat_hd_df)) %>%
    left_join(diff_mean_hd, by = "stratum") %>%
    select(weight, diff_mean);
  
  #Calculate the ATE
  ATE_hd <- sum(diff_weight_hd$diff_mean * diff_weight_hd$weight)
})

time_hd <-sum(hd_prep)


#Low Dimensional Data

ld_prep <- system.time({
  
  #Stratify the Data by Propensity score
  ld_strat_divider <- n_strat/nrow(ps_ld_df);
  strat_ld_df <- ps_ld_df %>% arrange(prop_score) %>%
    mutate(stratum =  as.integer((1:n() -.5)*ld_strat_divider ) + 1);


  #Differences in means
  diff_mean_ld <- strat_ld_df %>%
    group_by(treatment, stratum) %>%
    summarise(mean_treat = mean(Y), .groups = "keep") %>%
    mutate(mean_treat= if_else(treatment == 0, -mean_treat, mean_treat)) %>%
    ungroup(treatment) %>%
    mutate(diff_mean = sum(mean_treat)) %>%
    filter(treatment == 0) %>%
    select(stratum, diff_mean);

  #Weights for each stratum
  diff_weight_ld <- strat_ld_df %>%
    group_by(stratum) %>%
    tally() %>%
    mutate(weight = n/nrow(strat_ld_df)) %>%
    left_join(diff_mean_ld, by = "stratum") %>%
    select(weight, diff_mean);
  
  #Calculate the ATE
  ATE_ld <- sum(diff_weight_ld$diff_mean * diff_weight_ld$weight)

}) 

time_ld <- sum(ld_prep)

```

### Alternate Method that performs regression on each stratum by Y with A and Vs. Then averages the coefficients 
### for A in each stratum to get the ATE

```{r}


n_strat <- 7

#High Dimensional Data


hd_prep_alt <- system.time({
  hd_strat_divider <- n_strat/nrow(ps_hd_df);
  
  #Append propensity score to the initial dataset

  hd_pscore <- matrix(ps_hd_df$prop_score, ncol = 1);
  hd_df_pscore <- cbind(highDim_data, hd_pscore);
  
  strat_hd_df_alt <- hd_df_pscore %>% arrange(hd_pscore) %>%
    mutate(stratum =  as.integer((1:n() -.5)*hd_strat_divider ) + 1) %>%
    select(-hd_pscore);
  
  strat_hd_reg <- strat_hd_df_alt %>% group_by(stratum) %>%
    do(strat_reg = lm(Y ~ A + .-stratum, data = .)) %>%
    mutate(coefs = list(strat_reg[["coefficients"]])) %>%
    select(-strat_reg) %>%
    summarize(ajz = coefs[["A"]], .groups = "drop");
 
  #Calculate the ATE
  ATE_hd_alt <-  mean(strat_hd_reg$ajz)
  
})

time_hd_alt <- sum(hd_prep_alt)

#Low Dimensional Data

ld_prep_alt <- system.time({
  
  ld_strat_divider <- n_strat/nrow(ps_ld_df);
  
  #Append propensity score to the initial dataset

  ld_pscore <- matrix(ps_ld_df$prop_score, ncol = 1);
  ld_df_pscore <- cbind(lowDim_data, ld_pscore);
  
  strat_ld_df_alt <- ld_df_pscore %>% arrange(ld_pscore) %>%
    mutate(stratum =  as.integer((1:n() -.5)*ld_strat_divider ) + 1) %>%
    select(-ld_pscore);
  
  strat_ld_reg <- strat_ld_df_alt %>% group_by(stratum) %>%
    do(strat_reg = lm(Y ~ A + .-stratum, data = .)) %>%
    mutate(coefs = list(strat_reg[["coefficients"]])) %>%
    select(-strat_reg) %>%
    summarize(ajz = coefs[["A"]], .groups = "drop")

  #Calculate the ATE
  ATE_ld_alt <-  mean(strat_ld_reg$ajz)
  
}) 

time_ld_alt <- sum(ld_prep_alt)
```

### Second Alternative method that performs regression on each stratum by Y and A

```{r}


n_strat <- 5

#High Dimensional Data


hd_prep_alt2 <- system.time({
  
  #Stratify the Data by Propensity score
  hd_strat_divider <- n_strat/nrow(ps_hd_df);
  strat_hd_df_alt2 <- ps_hd_df %>% arrange(prop_score) %>%
    mutate(stratum =  as.integer((1:n() -.5)*hd_strat_divider ) + 1);
  
  #Perform Regression on each Stratum
  reg_stratum_hd <- strat_hd_df_alt2 %>%
    group_by(stratum) %>%
    do(tidy(lm(Y ~ treatment, .)));
  
  #Will end up with a matrix of regression terms alternating with (Intercept) and Y.
  #Since we are subtracting the point on the regression where Y(our x term) is 0 from where Y is 1,
  #We are doing this type of equation:      Result = (Intercept + (1* Y)) - (Intecept) = Y
  #Thus, we only need the estimate for the Y's
  
  reg_est_result_hd <- reg_stratum_hd %>%
    filter(term == "treatment") %>%
    select(stratum, estimate);
  
  #Calculate the ATE
  ATE_hd_alt2 <- sum(reg_est_result_hd$estimate)/n_strat
})

time_hd_alt2 <- sum(hd_prep_alt2)


#Low Dimensional Data

ld_prep_alt2 <- system.time({
  
  #Stratify the Data by Propensity score
  ld_strat_divider <- n_strat/nrow(ps_ld_df);
  strat_ld_df_alt2 <- ps_ld_df %>% arrange(prop_score) %>%
    mutate(stratum =  as.integer((1:n() -.5)*ld_strat_divider ) + 1);


  #Perform Regression on each Stratum
  reg_stratum_ld <- strat_ld_df_alt2 %>%
    group_by(stratum) %>%
    do(tidy(lm(Y ~ treatment, .)));
  
  #Will end up with a matrix of regression terms alternating with (Intercept) and Y.
  #Since we are subtracting the point on the regression where Y(our x term) is 0 from where Y is 1,
  #We are doing this type of equation:      Result = (Intercept + (1* Y)) - (Intecept) = Y
  #Thus, we only need the estimate for the Y's
  
  reg_est_result_ld <- reg_stratum_ld %>%
    filter(term == "treatment") %>%
    select(stratum, estimate);
  
  #Calculate the ATE
  
  ATE_ld_alt2 <- sum(reg_est_result_ld$estimate)/n_strat
}) 

time_ld_alt2 <- sum(ld_prep_alt2)

```


